<a href="https://colab.research.google.com/github/imkmaurya/Spam_mail_prediction/blob/main/Spam_mail_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [218]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [219]:
raw_mail_data=pd.read_csv("mail_data.csv")
raw_mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [220]:
mail_data=raw_mail_data.where((pd.notnull(raw_mail_data)),'')

In [221]:
mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

In [222]:
mail_data['Category']=mail_data['Category'].map({'ham':0,'spam':1})

ham->> 0,
spam->> 1

In [223]:
mail_data.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [224]:
X=mail_data['Message']
y=mail_data['Category']

In [225]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [226]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4457,), (1115,), (4457,), (1115,))

In [227]:
feature_extract=TfidfVectorizer(min_df=1,stop_words="english",lowercase=True)

In [228]:
X_train_feature=feature_extract.fit_transform(X_train)
X_test_feature=feature_extract.transform(X_test)

y_test=y_test.astype('int')
y_train=y_train.astype('int')

In [229]:
X_train_feature

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34840 stored elements and shape (4457, 7440)>

In [230]:
model=LogisticRegression()
model.fit(X_train_feature,y_train)

LogisticRegression()

In [231]:
y_pred=model.predict(X_test_feature)
y_train_pred=model.predict(X_train_feature)

In [232]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Category, Length: 5572, dtype: int64

In [233]:
y_test

3245    0
944     0
1044    0
2484    0
812     0
       ..
4264    0
2439    0
5556    0
4205    0
4293    0
Name: Category, Length: 1115, dtype: int64

In [234]:
print("accuracy score for training:",accuracy_score(y_train,y_train_pred))
print("accuracy score for testing:",accuracy_score(y_test,y_pred))

accuracy score for training: 0.9670181736594121
accuracy score for testing: 0.967713004484305

In [235]:
input_mail=["Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
]

feature_input=feature_extract.transform(input_mail)

prediction=model.predict(feature_input)
print(prediction)

[0]

In [236]:
if(prediction==0):
  print("ham")
else:
  print("spam")

ham

In [238]:
import pickle
with open("model.pkl","wb") as f:
  pickle.dump(model,f)

In [239]:
import pickle

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(feature_extract, f)